#!/Users/mzhafn/.pyenv/versions/venv/bin/python

import argparse
from common import jira, jira_names

parser = argparse.ArgumentParser(
    description="Set Jira field",
    formatter_class=argparse.ArgumentDefaultsHelpFormatter,
)
parser.add_argument(
    "issue", help="Jira issue"
)
parser.add_argument(
    "name", help="Field name"
)
parser.add_argument(
    "value", help="Field value"
)
args = parser.parse_args()

name = jira_names.get(args.name, args.name)

try:
    value = float(args.value)
except ValueError:
    value = args.value

issue = jira.issue(args.issue)
print(f"{args.issue}: {issue.fields.summary}")
print(f"{name} = {getattr(issue.fields, name)}", end="")
issue.update({name: value})
print(f" => {getattr(issue.fields, name)}")


